### ISSUE TITLE
Typo "premitive"

### ISSUE THREAD

**Issue by ulidtko** [takenobu-hs/haskell-ghc-illustrated#1]
Hi, great presentation!

There's a typo on slide titled "newEmptyMVar":

> (1) call the Runtime premitive

should be

> (1) call the Runtime primitive

**Comment by ulidtko** [comment]
Another one, slide "Create each layers":

> initCapaility

should be

> initCapability

**Comment by takenobu-hs** [comment]
Sorry late response.

Thank you for your detail feedback.
I corrected them on v0.01.1

Your feedback helped me :-)
