### ISSUE TITLE
`TRecEntry`

### ISSUE THREAD

**Issue by fryguybob** [takenobu-hs/haskell-ghc-illustrated#2]
On the slide _STM, TVar data structure_, the `TRecEntry` structure is shown pointing to two `StgTVar`s.  It should be pointing to a single `StgTVar` and potentially two heap objects:

``` .c
typedef struct {
  StgTVar                   *tvar;
  StgClosure                *expected_value;
  StgClosure                *new_value;
#if defined(THREADED_RTS)
  StgInt                     num_updates;
#endif
} TRecEntry;
```

(also, this work is awesome!)

**Comment by takenobu-hs** [comment]
Hi Ryan,

Thank you very much for your advice!
I'm glad to be able to know it  :smiley:

I'll update it for next version.
(my work is very slow:smile: )

Thanks!

**Comment by takenobu-hs** [comment]
I fixed slide 90. Sorry too late.
Thanks Ryan.
